# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  configuration: release
  sqlinstance: localhost
  database: SQL2019DB
  azuredatabase: AzureDB
  artifactname: SQL2019
  azureartifactname: AzureSQLDB

trigger:
- master
- main
- kcdemobranch

stages:
- stage: AzureBuild
  displayName: 'Build Azure dacpac'
  jobs:
    - job: 'BuildAzureSQLDB'
      displayName: 'Build Azure SQL DB dacpac'
      variables:
        variables:
        agentpool: 'kchant DevOps Duet'
      pool:
        vmImage: vs2017-win2016

      steps:
      - task: VSBuild@1
        displayName: 'Build kcdemoproject for Azure SQL Database'
        inputs:
          solution: kcdemodbproject.sqlproj
          configuration: $(configuration)

      - task: CopyFiles@2
        displayName: "Copy files to AzureDB artifact subfolder"
        inputs:
          Contents: |
            **\bin\$(configuration)\*.*
          TargetFolder: '$(Build.ArtifactStagingDirectory)\$(azureartifactname)'
          FlattenFolders: true
          OverWrite: true

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Azure SQL artifact'
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)\$(azureartifactname)'
          ArtifactName: $(azureartifactname)
          publishLocation: 'Container'

- stage: DeployAzureDB
  dependsOn: AzureBuild
  displayName: 'Deploy Azure SQL DB'

  jobs:
    - job: 'DeployAzureDB'
      displayName: 'Deploy Azure SQL DB'
      variables:
        variables:
        agentpool: 'kchant DevOps Duet'
        dacpacpath: $(System.ArtifactsDirectory)/$(azureartifactname)
        datadacpacfile: kcdemoproject.dacpac

      pool: $(agentpool)
        
      steps:
      - task: DownloadBuildArtifacts@0
        displayName: 'Dowload Artifacts'
        inputs:
          buildType: 'current'
          downloadType: 'specific'
          artifactName:  '$(azureartifactname)'
          downloadPath: '$(System.ArtifactsDirectory)'

      - task: SqlAzureDacpacDeployment@1
        displayName: 'Install DACPAC on Azure SQL DB'
        inputs:
          azureSubscription: 'Visual Studio Enterprise Subscription(170486b8-8385-407d-86a6-cff8864ec100)'
          AuthenticationType: 'server'
          ServerName: 'kcdemosrv.database.windows.net'
          DatabaseName: '$(azuredatabase)'
          SqlUsername: '$(azureuser)'
          SqlPassword: '$(azuresqlpw)'
          deployType: 'DacpacTask'
          DeploymentAction: 'Publish'
          DacpacFile: '$(dacpacpath)/$(datadacpacfile)'
          AdditionalArguments: '/p:IncludeCompositeObjects=true'
          IpDetectionMethod: 'AutoDetect'