# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  configuration: release
  sqlinstance: localhost
  database: SQL2019DB
  azuredatabase: AzureDB
  artifactname: SQL2019
  azureartifactname: AzureSQLDB

trigger:
- master
- main
- kcdemobranch

stages:
- stage: Build
  displayName: 'Build SQL 2019 dacpac'
  jobs:
    - job: 'Solution'

      pool:
        vmImage: vs2017-win2016

      steps:
      - task: VSBuild@1
        displayName: 'Build kcdemoproject for SQL Server 2019'
        inputs:
          solution: kcdemodbproject.sqlproj
          configuration: $(configuration)

      - task: CopyFiles@2
        displayName: "Copy files to SQL2019 artifact subfolder"
        inputs:
          Contents: |
            **\bin\$(configuration)\*.*
          TargetFolder: '$(Build.ArtifactStagingDirectory)\$(artifactname)'
          FlattenFolders: true
          OverWrite: true

      - task: PublishBuildArtifacts@1
        displayName: 'Publish SQL2019 artifact'
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)\$(artifactname)'
          ArtifactName: $(artifactname)
          publishLocation: 'Container'

- stage: SQL2019
  displayName: 'Local SQL Server 2019 update'

  jobs:
    - job: 'Deploy2019'
      displayName: 'Update SQL Server 2019 database'
      variables:
        variables:
        agentpool: 'kchant DevOps Duet'
        dacpacpath: $(System.ArtifactsDirectory)/$(artifactname)
        datadacpacfile: kcdemodbproject.dacpac

      pool: $(agentpool)
        
      steps:
      - task: DownloadBuildArtifacts@0
        displayName: 'Dowload Artifacts'
        inputs:
          buildType: 'current'
          downloadType: 'specific'
          downloadPath: '$(System.ArtifactsDirectory)'

      - task: SqlDacpacDeploymentOnMachineGroup@0
        displayName: 'Install DACPAC'
        inputs:
          TaskType: 'dacpac'
          DacpacFile: '$(dacpacpath)/$(datadacpacfile)'
          TargetMethod: 'server'
          ServerName: 'localhost,1443'
          DatabaseName: '$(database)'
          AuthScheme: 'sqlServerAuthentication'
          SqlUsername: 'sa'
          SqlPassword: $(sqlsapw)
          AdditionalArguments: '/p:IncludeCompositeObjects=true'

- stage: AzureBuild
  dependsOn: Build
  displayName: 'Build Azure SQL DB dacpac file'

  jobs:
    - job: 'BuildAzureSQLDB'
      displayName: 'Build Azure SQL DB dacpac'
      variables:
        variables:
        agentpool: 'kchant DevOps Duet'
        sourcepath: $(database)-Data
        stagingarea: $(Build.ArtifactStagingDirectory)\staging
        destinationpath: $(azuredatabase)
        dacpacpath: $(System.ArtifactsDirectory)/$(artifactname)
        datadacpacfile: $(azuredatabase).dacpac
        datapublishfile: $(dacpacpath)/$(azuredatabase).publish.xml

      pool: $(agentpool)
        
      steps:
      - task: CopyFiles@2
        displayName: "Copy sqlproj to staging area for Azure-Data"
        inputs:
          Contents: |
            $(azuredatabase)\*.sqlproj
          TargetFolder: '$(stagingarea)'
          FlattenFolders: true
          OverWrite: true

      - task: CopyFiles@2
        displayName: "Copy dbo to staging area for Azure-Data"
        inputs:
          Contents: |
            dbo\**
          TargetFolder: '$(stagingarea)\dbo'
          FlattenFolders: false
          OverWrite: true
      - task: CopyFiles@2
        displayName: "Copy SalesLT to staging area"
        inputs:
          Contents: |
            SalesLT\**
          TargetFolder: '$(stagingarea)\SalesLT'
          FlattenFolders: false
          OverWrite: true
      - task: CopyFiles@2
        displayName: "Copy Security to staging area"
        inputs:
          Contents: |
            Security\**
          TargetFolder: '$(stagingarea)\Security'
          FlattenFolders: true
          OverWrite: true


      - task: VSBuild@1
        displayName: 'Build Azure-Data project'
        inputs:
          solution: $(stagingarea)/kcdemoazureproject.sqlproj
          configuration: $(configuration)

      - task: CopyFiles@2
        displayName: "Copy files to artifact directory"
        inputs:
          Contents: |
            **\$(stagingarea)\bin\$(configuration)\*.*
          TargetFolder: '$(Build.ArtifactStagingDirectory)\$(azureartifactname)'
          FlattenFolders: true
          OverWrite: true

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Azure SQL database artifact'
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: $(azureartifactname)
          publishLocation: 'Container'

- stage: DeployAzureDB
  dependsOn: Build
  displayName: 'Deploy to Azure SQL DB'

  jobs:
    - job: 'Deploy2019'
      displayName: 'Deploy Azure SQL DB'
      variables:
        variables:
        agentpool: 'kchant DevOps Duet'
        dacpacpath: $(System.ArtifactsDirectory)/$(azureartifactname)
        datadacpacfile: kcdemoazureproject.dacpac

      pool: $(agentpool)
        
      steps:
      - task: DownloadBuildArtifacts@0
        displayName: 'Dowload Artifacts'
        inputs:
          buildType: 'current'
          downloadType: 'specific'
          artifactName:  '$(azureartifactname)'
          downloadPath: '$(System.ArtifactsDirectory)'

      - task: SqlAzureDacpacDeployment@1
        displayName: 'Install DACPAC on Azure SQL DB'
        inputs:
          azureSubscription: 'Visual Studio Enterprise Subscription(170486b8-8385-407d-86a6-cff8864ec100)'
          AuthenticationType: 'server'
          ServerName: 'kcdemosrv.database.windows.net'
          DatabaseName: '$(azuredatabase)'
          SqlUsername: '$(azureuser)'
          SqlPassword: '$(azuresqlpw)'
          deployType: 'DacpacTask'
          DeploymentAction: 'Publish'
          DacpacFile: '$(dacpacpath)/$(datadacpacfile)'
          AdditionalArguments: '/p:IncludeCompositeObjects=true'
          IpDetectionMethod: 'AutoDetect'
