# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  configuration: release
  sqlinstance: localhost
  database: SQL2019DB
  azuredatabase: AzureDB
  artifactname: SQL2019
  azureartifactname: AzureSQLDB

trigger:
- master
- main
- kcdemobranch

stages:
- stage: Build
  displayName: 'Build SQL 2019 dacpac'
  jobs:
    - job: 'Solution'
      variables:
        variables:
        agentpool: 'kchant DevOps Duet'
      pool: $(agentpool)

      steps:
      - task: VSBuild@1
        displayName: 'Build kcdemoproject for SQL Server 2019'
        inputs:
          solution: kcdemodbproject.sqlproj
          configuration: $(configuration)

      - task: CopyFiles@2
        displayName: "Copy files to SQL2019 artifact subfolder"
        inputs:
          Contents: |
            **\bin\$(configuration)\*.*
          TargetFolder: '$(Build.ArtifactStagingDirectory)\$(artifactname)'
          FlattenFolders: true
          OverWrite: true

      - task: PublishBuildArtifacts@1
        displayName: 'Publish SQL2019 artifact'
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)\$(artifactname)'
          ArtifactName: $(artifactname)
          publishLocation: 'Container'