# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  configuration: release
  sqlinstance: localhost
  database: SQL2019DB
  azuredatabase: AzureDB
  artifactname: SQL2019
  azureartifactname: AzureSQLDB

trigger:
- master
- main
- kcdemobranch


